name: "Build and release firmware"

on: 
  workflow_dispatch:
    inputs:
      releaseBody:
        description: 'Additional release text'
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build in docker container
        id: docker_build
        uses: ./.github/actions/
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: precompiled-firmware-files
          path: |
            qmk_firmware/nullbitsco_*.hex
            qmk_firmware/nullbitsco_*.uf2
      - name: Get current date
        id: date
        run: echo "date=$(date +'%m/%d/%Y')"  >> $GITHUB_OUTPUT
      - name: Generate release text
        id: release_text
        run: >
          echo "release_text=$(echo '<b>Precompiled firmware files for nullbits keyboards</b><br><br>
          Download a firmware file by expanding "Assets", right clicking, and choosing "Save File As" or "Save Link As".
          <br>${{ github.event.inputs.releaseBody }}
          <br>Released on ${{ steps.date.outputs.date }}.
          <br><br>${{ steps.docker_build.outputs.commits }}')" >> $GITHUB_OUTPUT
      - name: Create release (AVR)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "qmk_firmware/nullbitsco_*.hex"
          allowUpdates: true
          artifactErrorsFailBuild: true
          body: ${{ steps.release_text.outputs.release_text }}
          tag: "latest-avr"
          name: "Precompiled Firmware Files (AVR)"
          token: ${{ secrets.GITHUB_TOKEN }}
          removeArtifacts: true
          makeLatest: true
      - name: Create release (RP2040)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "qmk_firmware/nullbitsco_*.uf2"
          allowUpdates: true
          artifactErrorsFailBuild: true
          body: ${{ steps.release_text.outputs.release_text }}
          tag: "latest-rp2040"
          name: "Precompiled Firmware Files (RP2040)"
          token: ${{ secrets.GITHUB_TOKEN }}
          removeArtifacts: true
