name: "Build and release firmware"

on: 
  workflow_dispatch:
    inputs:
      releaseBody:
        description: 'Additional release text'
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build in docker container
        id: docker_build
        uses: ./.github/actions/
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: precompiled-firmware-files
          path: |
            qmk_firmware/nullbitsco_*.hex
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m/%d/%Y')"
      - name: Generate release text
        id: release_text
        run: >
          echo "::set-output name=release_text::$(echo '<b>Precompiled firmware files for nullbits keyboards</b><br><br>
          Download a firmware file by expanding "Assets", right clicking, and choosing "Save File As" or "Save Link As".
          <br>${{ github.event.inputs.releaseBody }}
          <br>Released on ${{ steps.date.outputs.date }}.
          <br><br>${{ steps.docker_build.outputs.commits }}')"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "qmk_firmware/nullbitsco_*.hex"
          allowUpdates: true
          artifactErrorsFailBuild: true
          body: ${{ steps.release_text.outputs.release_text }}
          tag: "latest"
          name: "Precompiled Firmware Files"
          token: ${{ secrets.GITHUB_TOKEN }}
          removeArtifacts: true
          makeLatest: true
